### ISSUE TITLE
elasticsearch query작성법 잘 아시는 분 계실까요?

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/Elastic_search-thymeleaf#1]
![today](https://user-images.githubusercontent.com/100353794/192325189-19fc94fe-4ce4-4c5d-8129-7157f5cce175.PNG)

GET /_search
{
    "_source": ["libraryName"],
    "query":{"match":{"isbn13":"9791167780423"}}
  
} @Query 부분에 이 코드를 적고 하고 싶은데 어떻게 하는지 잘 모르겠습니다..

**Comment by Lee1231234** [comment]
query builder의 대한 내용을 찾아보세요 상당히 많은 레퍼런스가 있습니다.
(https://juntcom.tistory.com/149)
