### ISSUE TITLE
도서목록을 1000개씩 받고 service에서 filter을 이용해 중복을 제거하는데 속도가 좀 느리네요

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/Elastic_search-thymeleaf#11]
![으악](https://user-images.githubusercontent.com/100353794/193639400-19dbfe97-6de8-45a5-8b5e-892e704c089a.PNG)
혹시 좋은 중복을 제거 할때 속도를 더 개선할 방법이 있을까요..? 
확실히.collapse보다는 filter을 이용해 중복을 제거하는것이 속도가 빨리 나옵니다. 또,  .collapse를 사용하면 중복을 제거하고 1000개의 도서 데이터들이 나오는데 사용자가 볼때에는 상위 몇 페이지의 도서들만 유효하기 때문에 이런 방법은 비효율적이기도 합니다.😀

**Comment by Lee1231234** [comment]
자바 필터스트림을 사용하는것보다 엘라스틱 서치에서 해결하는것이 더 빠를겁니다.

**Comment by DongDongShin** [comment]
> 자바 필터스트림을 사용하는것보다 엘라스틱 서치에서 해결하는것이 더 빠를겁니다.

헉.. 감사합니다.알려주신대로  CollapseField를 사용하면 의도된대로 중복 제거가 안되는것을   CollapseBuild을 쓰니깐 중복제거 잘 됩니다.~!~!
