### ISSUE TITLE
멘토님 여기입니다) redis를 쓰는이유?

### ISSUE THREAD

**Issue by Lee1231234** [library-search-machine/Elastic_search-thymeleaf#15]
mysql로 JWT토큰을 사용해 로그인 로그아웃을 만들수있음에도 불구하고 redis를 쓰는 이유가 혹시 TTL때문인가요? 아니면 그 외의 것에서 다른 장점을 얻을수있나요? 캐시같은것에서 이득을 볼수 있나 싶습니다.

현재 로그인 브랜치는 feature/login입니다.

제가 생각한 것은 mysql에 회원가입정보를 저장해두고 로그인할때 redis ReflshToken JWT를 넣어 놓은뒤  페이지를 옮길때마다  redis에서 검증하고 로그인을 유지하는 방식을 생각하고있습니다.

**Comment by J-minkuk** [comment]
refreshToken을 사용한다는 것은 IO가 많이 일어날 수 있고, refreshToken invalid 관리도 해야하는데요.
RDBMS에 저장한다면 주기적으로 refreshToken invalid 작업을 따로 해야하지 않을까요??

**Comment by Lee1231234** [comment]
주기적인 관리와 유효성 검증을 TTL과 캐시를 통해서 할수 있겠군요 감사합니다.
