### ISSUE TITLE
결과값이 10000개 이상일 때 issue발생

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/Elastic_search-thymeleaf#2]
대부분의 키워드에서는 발생하지 않지만 검색어가 "고양"이나 "나무" 등등 자주 쓰이는 명사일 경우에는 결괏값이 10000개가 초과됩니다. elastricsearch에서 기본으로 제공하는 쿼리문을 보니  "max_determinized_states":10000" 로 검색 결과값 갯수를 10000개로 제외하는데 어떻게 해야할까요...?? 아마 기본쿼리를 날리지 않고 @Query로 쿼리문을 customize해야 할 것 같긴 하네요.
![dmdkf](https://user-images.githubusercontent.com/100353794/192449096-5d999d6f-0072-4380-afe5-08c7c067c378.PNG)

**Comment by Lee1231234** [comment]
여러 방법이 있을것같습니다. 그렇지만 search_after의 방법이 이 프로젝트에 가장 적합해 보이네요

**Comment by DongDongShin** [comment]
> 여러 방법이 있을것같습니다. 그렇지만 search_after의 방법이 이 프로젝트에 가장 적합해 보이네요

아하 감사합니다~~
